version: '3.1'
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./conf/php
    volumes:
      - ./www:/var/www/html
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: website
    volumes:
      - database:/var/lib/mysql
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - 8080:80
volumes:
  database: