version: '3.1'

services:
  wordpress:
    image: wordpress
    # build: .
    restart: always
    ports:
      - "8080:80"
    environment:
      PHP_EXTENSION_XDEBUG: 1
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: edisc
      WORDPRESS_DB_PASSWORD: edisc
      WORDPRESS_DB_NAME: wordpress
    volumes:
    - ./wordpress:/var/www/html
    - ./php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: edisc
      MYSQL_PASSWORD: edisc
      MYSQL_ROOT_PASSWORD: edisc
    volumes:
      - ./mysql:/var/lib/mysql


